### ISSUE TITLE
epic: Conversation list screen improvements

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot-mobile-app#507]
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/382
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/421
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/397

**Comment by muhsin-k** [comment]
### **UI Mockups**

### **Conversation List Screen**


<img src="https://user-images.githubusercontent.com/12408980/196615906-cbe78832-b066-4979-a04f-7e2361d2fc89.PNG">

### **Filters**

**Filter by inbox**

![IMG_6759](https://user-images.githubusercontent.com/12408980/196616778-8ed4901f-982a-4114-bd34-b5b9370a9d3f.PNG)

**Filter by conversation status**

![IMG_6758](https://user-images.githubusercontent.com/12408980/196616767-778350b1-19b4-4f2c-a18e-2f0c5bd73260.PNG)


**Filter by assignee type**

![IMG_6757](https://user-images.githubusercontent.com/12408980/196616730-8f8c1194-5c9c-4186-95b8-79d3c7fa423f.PNG)

**Comment by muhsin-k** [comment]
### Objectives
- Make the conversation list screen performant.
- Add the filters on the same screen for better UX.
- Avoid fetching the data if data already exists

### Tasks 

- Normalize the state with the Redux tool kit
- Add filters on the same screen
- Create custom components without relying on the third-party framework
- Replace the Eva icon with fluent icons for consistency with the dashboard
- Replace Flat list with Flash list for better performance
- Add the support for theming (Light and Dark)

### Blockers
- The current RN version has issues with the flipper(debugging tool). Consider upgrading the RN version to the latest version
