### ISSUE TITLE
epic: Email improvements

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot-mobile-app#510]
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/439
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/475
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/352
- [ ] #511
